### 使用方法
# homedir/.vagrant.d/ にこのファイルを配置する
# 各box用の秘密鍵を下記 `private_key_path`で指定しているところに配置する

Vagrant.configure("2") do |config|
  config.vm.define "baukis" do |baukis|
    baukis.vm.provider :virtualbox do |vb|
      vb.customize [ 'modifyvm', :id, '--memory',1024 ]
    end
    #baukis.ssh.private_key_path = "~/vagrantBox/default.key"
    baukis.vm.network "forwarded_port", guest: 3000, host: 3000
    baukis.vm.network "private_network", ip: "192.168.33.2"
    baukis.vm.synced_folder ".", "/vagrant", nfs: true
  end
  config.vm.define "bois" do |bois|
    bois.vm.provider :virtualbox do |vb|
      vb.customize [ 'modifyvm', :id, '--memory',1024 ]
    end
    #bois.ssh.private_key_path = "~/vagrantBox/default.key"
    bois.vm.network "forwarded_port", guest: 3000, host: 4000
    bois.vm.network "private_network", ip: "192.168.33.11"
    bois.vm.synced_folder ".", "/vagrant", nfs: true
  end
  config.vm.define "fweb-web" do |web|
    web.vm.provider :virtualbox do |vb|
      vb.customize [ 'modifyvm', :id, '--memory',1024 ]
    end
    web.ssh.private_key_path = "~/vagrantBox/fweb_boxes.key"
    web.vm.network "forwarded_port", guest: 3000, host: 5000
    web.vm.synced_folder ".", "/vagrant", nfs: true
  end
  config.vm.define "fweb-db" do |db|
    db.vm.synced_folder ".", "/vagrant", disabled: true
    db.ssh.private_key_path = "~/vagrantBox/fweb_boxes.key"
  end
  config.vm.define "idaccess" do |idaccess|
    idaccess.vm.synced_folder ".", "/vagrant", disabled: true
    idaccess.ssh.private_key_path = "~/vagrantBox/fweb_boxes.key"
  end
  config.vm.define "oldfweb" do |oldfweb|
    oldfweb.vm.provider :virtualbox do |vb|
      vb.customize [ 'modifyvm', :id, '--memory',1024 ]
    end
    #oldfweb.ssh.private_key_path = "~/vagrantBox/default.key"
    oldfweb.vm.network "private_network", ip: "192.168.33.31"
    oldfweb.vm.synced_folder ".", "/usr/local/bbtportal/bbtsite/", nfs: true
  end
end
